### PR TITLE
Fixed ZignAccessTokenProvider

### LINKED ISSUE #208: ZignAccessTokenProvider succeeds with empty string on zign command failure
`ZignAccessTokenProvider` does not check the exit code of the `zign` command. Instead returns the empty output of the process as a succcess.

### LINKED ISSUE #209: ZignAccessTokenProvider does not work
I think the `zign` command no longer accepts `uid` as an argument to the `token` subcommand. It should just be `zign token` now.

### PR DESCRIPTION
**Pull request by amrhassan**
There were no existing tests for this part of the code. Do I need to still provide one?

Closes #208, Closes #209

### CODE REVIEW

File: fahrschein/src/main/java/org/zalando/fahrschein/ZignAccessTokenProvider.java [hunk 1]
```diff
@@ -42,18 +43,25 @@ private static String readAll(InputStream inputStream) throws IOException {
...
+            throw new IOException("zign process took longer than 5 seconds to exit");
         }
     }
 
     private static Entry update(@Nullable Entry entry)  {
         final long now = System.currentTimeMillis();
         try {
-            return entry == null || entry.timestamp < now - CACHE_DURATION ? new Entry(now, zign()) : entry;
+            final Entry newEntry = entry == null || entry.timestamp < now - CACHE_DURATION ? new Entry(now, zign()) : entry;
+            LOG.debug("Refreshed token from zign");
```
Comment (jhorstmann) [inline fahrschein/src/main/java/org/zalando/fahrschein/ZignAccessTokenProvider.java]: This would now log every time, independent of whether the `zign` binary was called.

File: fahrschein/src/main/java/org/zalando/fahrschein/ZignAccessTokenProvider.java [hunk 2]
```diff
@@ -42,18 +43,25 @@ private static String readAll(InputStream inputStream) throws IOException {
...
-        final Process zign = new ProcessBuilder("zign", "token", "uid").start();
+        final Process zign = new ProcessBuilder("zign", "token").start();
         try (final InputStream inputStream = zign.getInputStream()) {
-            return readAll(inputStream).trim();
-        } finally {
-            LOG.debug("Refreshed token from zign");
+            final String output = readAll(inputStream).trim();
+            zign.waitFor(5, TimeUnit.SECONDS);
+            if (zign.exitValue() != 0) {
+                throw new IOException("zign exit code was non-zero");
```
Comment (jhorstmann) [inline fahrschein/src/main/java/org/zalando/fahrschein/ZignAccessTokenProvider.java]: Could include the exit code in the exception message

**Comment by jhorstmann** [comment]
@amrhassan Thanks for the contribution, I added two small comments, otherwise this looks good.

File: fahrschein/src/main/java/org/zalando/fahrschein/ZignAccessTokenProvider.java (hunk 2 above)
Comment (amrhassan) [reply fahrschein/src/main/java/org/zalando/fahrschein/ZignAccessTokenProvider.java]: Sure

File: fahrschein/src/main/java/org/zalando/fahrschein/ZignAccessTokenProvider.java (hunk 1 above)
Comment (amrhassan) [reply fahrschein/src/main/java/org/zalando/fahrschein/ZignAccessTokenProvider.java]: Right. Will change.

**Comment by jhorstmann** [comment]
:+1:
